
#defining the experiment and where the geometry is
/rat/db/set DETECTOR experiment "basic_test"
/rat/db/set DETECTOR geo_file "basic_test/basic_test.geo"

/run/initialize

#Visualization
/vis/open OGLSQt
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/viewer/set/upVector 0.0 0.0 1.0
/vis/viewer/set/viewpointThetaPhi -90 135 
/vis/viewer/set/style s
/vis/viewer/flush

# BEGIN EVENT LOOP
/rat/proc simpledaq
/rat/proc count
/rat/procset update 10

/rat/proclast outroot
/rat/procset file "basic_test.root"
#END EVENT LOOP

/generator/add combo gun2:point

#creates neutrons from 10 MeV to 10 MeV with momentum in the x direction and no angle

/generator/vtx/set neutron  1 0 0 0 10.0 10.0
/generator/pos/set 0 0 0

/run/beamOn 10000
